#!/usr/bin/env python3
"""
Create Figure 6 (main paper): OOD-only budget-sweep metrics in a compact 2-panel layout.

Inputs (generated by `scripts/evaluate/sweep_alpha.py`):
  - Coverage error (macro MAE), per task:
      outputs/sweeps_fullrange/eval_p4_alpha{A}/k{K}/summaries/*_summary.csv
      (uses `MAE_OOS_macro`)
  - Pinball loss, per task:
      outputs/sweeps_fullrange/eval_p4_alpha{A}/k{K}/*__pinball_sigmoid.csv
      (uses `split == "val"` as OOD)

Outputs:
  - outputs/figures_main_paper/figure6_main_paper.pdf
  - outputs/figures_main_paper/figure6_main_paper.png
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np

try:
    import matplotlib.pyplot as plt  # type: ignore
    from matplotlib.lines import Line2D  # type: ignore
except Exception as e:  # pragma: no cover
    raise SystemExit("This script requires matplotlib.") from e


# Import bootstrap from `scripts/` by putting the scripts dir on sys.path.
SCRIPTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)
from _bootstrap import ensure_repo_root_on_path  # type: ignore

REPO_ROOT = ensure_repo_root_on_path(__file__)

from skill_frontier.plotting.paper_style import apply_rcparams, STYLE_FIGURE6, TITLE_BBOX_MAIN_PAPER  # noqa: E402
from skill_frontier.plotting.plot_utils import ensure_dir, save_figure  # type: ignore
from skill_frontier.plotting.plot_paths import FIGURES_MAIN_PAPER_DIR  # noqa: E402
from skill_frontier.plotting.panel_style import apply_panel_style  # noqa: E402
from skill_frontier.io.task_mappings import MAIN_TASKS, order_tasks  # noqa: E402


# -----------------------------------------------------------------------------
# CONFIG (match Figures 1/4/5/7)
# -----------------------------------------------------------------------------

FIG_WIDTH = 7.0
FIG_HEIGHT = 2.6
DPI = 300

SUBPLOT_ADJUST = dict(left=0.09, right=0.98, bottom=0.15, top=0.93, wspace=0.28)

STYLE = STYLE_FIGURE6

TITLE_BBOX = TITLE_BBOX_MAIN_PAPER

TASK_ORDER: Sequence[str] = tuple(MAIN_TASKS)


def _configure_rcparams() -> None:
    apply_rcparams("figure6")


def _discover_alpha_dirs(base_dir: str) -> List[Tuple[int, str]]:
    pat = re.compile(r"^eval_p4_alpha(\d+)$")
    out: List[Tuple[int, str]] = []
    if not os.path.isdir(base_dir):
        raise FileNotFoundError(f"Missing sweeps directory: {base_dir}")
    for name in os.listdir(base_dir):
        m = pat.match(name)
        if not m:
            continue
        alpha = int(m.group(1))
        out.append((alpha, os.path.join(base_dir, name)))
    out.sort(key=lambda t: t[0])
    return out


def _read_first_row_csv(path: str) -> Dict[str, str]:
    with open(path, "r", newline="") as f:
        r = csv.DictReader(f)
        return next(r)


def _read_task_oos_mae(kdir: str) -> Dict[str, float]:
    """Read per-task OOD macro MAE from a single k directory."""
    out: Dict[str, float] = {}
    summaries_dir = os.path.join(kdir, "summaries")
    scan_dir = summaries_dir if os.path.isdir(summaries_dir) else kdir
    if not os.path.isdir(scan_dir):
        return out
    for fn in os.listdir(scan_dir):
        if not (fn.endswith("_summary.csv") or fn.endswith("__summary.csv")):
            continue
        row = _read_first_row_csv(os.path.join(scan_dir, fn))
        task = (row.get("task") or "").strip()
        if not task:
            continue
        raw = row.get("MAE_OOS_macro", "")
        try:
            val = float(raw) if raw not in ("", None) else float("nan")
        except Exception:
            val = float("nan")
        out[task] = val
    return out


def _read_task_oos_mae_period4(eval_base: str) -> Dict[str, float]:
    """Average per-task OOD macro MAE over k=1..3."""
    accum: Dict[str, List[float]] = {}
    for k in (1, 2, 3):
        kdir = os.path.join(eval_base, f"k{k}")
        vals = _read_task_oos_mae(kdir)
        for task, v in vals.items():
            accum.setdefault(task, []).append(v)
    out: Dict[str, float] = {}
    for task, vs in accum.items():
        arr = np.asarray(vs, float)
        out[task] = float(np.nanmean(arr)) if arr.size else float("nan")
    return out


def _read_task_oos_pinball(kdir: str) -> Dict[str, float]:
    """Read per-task OOD pinball loss (val split) from a single k directory."""
    out: Dict[str, float] = {}
    if not os.path.isdir(kdir):
        return out
    for fn in os.listdir(kdir):
        if not fn.endswith("__pinball_sigmoid.csv"):
            continue
        path = os.path.join(kdir, fn)
        try:
            with open(path, "r", newline="") as f:
                rows = list(csv.DictReader(f))
        except Exception:
            continue
        raw_val = next((r.get("L_sigmoid") for r in rows if r.get("split") == "val"), None)
        try:
            val = float(raw_val) if raw_val not in (None, "", "nan", "NaN") else float("nan")
        except Exception:
            val = float("nan")
        task = fn.replace("__pinball_sigmoid.csv", "")
        out[task] = val
    return out


def _read_task_oos_pinball_period4(eval_base: str) -> Dict[str, float]:
    """Average per-task OOD pinball loss over k=1..3."""
    accum: Dict[str, List[float]] = {}
    for k in (1, 2, 3):
        kdir = os.path.join(eval_base, f"k{k}")
        vals = _read_task_oos_pinball(kdir)
        for task, v in vals.items():
            accum.setdefault(task, []).append(v)
    out: Dict[str, float] = {}
    for task, vs in accum.items():
        arr = np.asarray(vs, float)
        out[task] = float(np.nanmean(arr)) if arr.size else float("nan")
    return out


def _build_series(
    alpha_dirs: Sequence[Tuple[int, str]],
    reader: callable,
) -> Tuple[List[int], List[str], Dict[str, List[float]], List[float]]:
    alphas = [a for a, _ in alpha_dirs]
    per_alpha: List[Dict[str, float]] = []
    tasks_all: set = set()
    for _a, base in alpha_dirs:
        vals = reader(base)
        per_alpha.append(vals)
        tasks_all |= set(vals.keys())
    tasks = order_tasks(tasks_all, TASK_ORDER, drop_missing=False)
    series = {t: [d.get(t, float("nan")) for d in per_alpha] for t in tasks}
    avg: List[float] = []
    for i in range(len(alphas)):
        arr = np.asarray([series[t][i] for t in tasks], float)
        avg.append(float(np.nanmean(arr)))
    return alphas, tasks, series, avg


def _set_log_ylim_from_series(ax: plt.Axes, series: Dict[str, List[float]], avg: Sequence[float]) -> None:
    vals: List[float] = []
    for ys in list(series.values()) + [list(avg)]:
        vals.extend([v for v in ys if np.isfinite(v) and v > 0])
    if not vals:
        return
    ymin = min(vals) * 0.90
    ymax = max(vals) * 1.10
    ax.set_ylim(ymin, ymax)
    ax.set_yscale("log")


def _plot_metric_panel(
    ax: plt.Axes,
    *,
    alphas: Sequence[int],
    series: Dict[str, List[float]],
    avg: Sequence[float],
    panel_title: str,
    ylabel: str,
    show_ylabel: bool,
) -> None:
    pos = np.arange(len(alphas), dtype=float)

    for ys in series.values():
        ax.plot(
            pos,
            ys,
            color=STYLE["task_line_color"],
            alpha=STYLE["task_line_alpha"],
            linewidth=STYLE["task_line_width"],
            zorder=2,
        )

    ax.plot(
        pos,
        avg,
        color=STYLE["avg_color"],
        alpha=STYLE["avg_alpha"],
        linewidth=STYLE["avg_line_width"],
        marker=STYLE["avg_marker"],
        markersize=STYLE["avg_markersize"],
        markeredgecolor=STYLE["avg_markeredgecolor"],
        markeredgewidth=STYLE["avg_markeredgewidth"],
        zorder=3,
    )

    ax.set_xticks(pos)
    ax.set_xticklabels([str(a) for a in alphas])
    ax.set_xlim(pos[0] - 0.2, pos[-1] + 0.2)

    ax.set_xlabel(r"$\alpha$ (% of evaluation budget)", fontsize=14, fontweight="bold", labelpad=4)
    if show_ylabel:
        ax.set_ylabel(ylabel, fontsize=14, fontweight="bold", labelpad=4)
    else:
        ax.set_ylabel("")

    title_obj = ax.set_title(panel_title, fontweight="bold", pad=12)
    title_obj.set_bbox(TITLE_BBOX)

    _set_log_ylim_from_series(ax, series, avg)


def main() -> None:
    ap = argparse.ArgumentParser(description="Create Figure 6 (OOD sweeps) for the main paper.")
    ap.add_argument(
        "--sweeps_dir",
        default=os.path.join(REPO_ROOT, "outputs", "sweeps_fullrange"),
        help="Base directory containing eval_p4_alpha* subfolders.",
    )
    ap.add_argument(
        "--out_dir",
        default=os.path.join(REPO_ROOT, str(FIGURES_MAIN_PAPER_DIR)),
        help="Output directory for the figure.",
    )
    args = ap.parse_args()

    _configure_rcparams()

    alpha_dirs = _discover_alpha_dirs(args.sweeps_dir)
    if not alpha_dirs:
        raise SystemExit(f"No eval_p4_alpha* directories found under: {args.sweeps_dir}")

    alphas, _tasks_mae, series_mae, avg_mae = _build_series(alpha_dirs, _read_task_oos_mae_period4)
    _alphas2, _tasks_pin, series_pin, avg_pin = _build_series(alpha_dirs, _read_task_oos_pinball_period4)

    fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH, FIG_HEIGHT), dpi=DPI)
    plt.subplots_adjust(**SUBPLOT_ADJUST)

    for ax in axes:
        apply_panel_style(ax, STYLE)

    _plot_metric_panel(
        axes[0],
        alphas=alphas,
        series=series_mae,
        avg=avg_mae,
        panel_title="(a) OOD Coverage Error",
        ylabel="Coverage error",
        show_ylabel=True,
    )
    _plot_metric_panel(
        axes[1],
        alphas=_alphas2,
        series=series_pin,
        avg=avg_pin,
        panel_title="(b) OOD Pinball Loss",
        ylabel="Pinball loss",
        show_ylabel=True,
    )

    # Compact legend (shared) in the left panel.
    handles = [
        Line2D([0], [0], color=STYLE["task_line_color"], alpha=STYLE["task_line_alpha"], linewidth=STYLE["task_line_width"]),
        Line2D(
            [0],
            [0],
            color=STYLE["avg_color"],
            alpha=STYLE["avg_alpha"],
            linewidth=STYLE["avg_line_width"],
            marker=STYLE["avg_marker"],
            markersize=STYLE["avg_markersize"],
            markeredgecolor=STYLE["avg_markeredgecolor"],
            markeredgewidth=STYLE["avg_markeredgewidth"],
        ),
    ]
    labels = ["Tasks", "Average"]
    axes[0].legend(
        handles,
        labels,
        loc="upper right",
        frameon=True,
        framealpha=0.9,
        edgecolor="#999999",
        fancybox=False,
        fontsize=12,
        ncol=1,
        handlelength=1.5,
        handletextpad=0.5,
        borderpad=0.5,
    )

    ensure_dir(args.out_dir)
    out_base = os.path.join(args.out_dir, "figure6_main_paper")
    save_figure(
        fig,
        args.out_dir,
        "figure6_main_paper",
        dpi=DPI,
        bbox_inches="tight",
        pad_inches=0.05,
        facecolor="white",
        edgecolor="none",
    )
    plt.close(fig)
    print(f"Saved: {out_base}.pdf and {out_base}.png")


if __name__ == "__main__":
    main()
